# render.yaml - Configurazione per evitare istanze multiple
services:
  - type: web
    name: captaincat-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    region: oregon
    # Configurazioni per singola istanza
    numInstances: 1
    maxMemoryGB: 0.5
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: WEB_CONCURRENCY
        value: "1"
      - key: BOT_TOKEN
        fromEnvVar: BOT_TOKEN
      - key: DATABASE_URL  
        fromEnvVar: DATABASE_URL
      - key: WEBAPP_URL
        fromEnvVar: WEBAPP_URL
    # Restart policy per stabilità
    autoDeploy: true
    restartPolicy: onFailure
