services:
  # Bot Telegram (Background Worker)
  - type: worker
    name: captaincat-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: captaincat-db
          property: connectionString
      - key: WEBAPP_URL
        value: https://captaincat-game.onrender.com
    region: oregon

  # Web App del gioco (Static Site)
  - type: web
    name: captaincat-game
    env: static
    buildCommand: echo "Static site ready"
    staticPublishPath: ./webapp
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database PostgreSQL
databases:
  - name: captaincat-db
    databaseName: captaincat_game
    user: captaincat_user
